name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: header.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header
  
  repositories:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: repositories

  acti_comm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: acti_comm.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: activity, community

  iso_calender:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: iso_calender.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  issue_pr_lang:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: issue_pr_lang.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: ""
          plugin_followup: yes
          plugin_languages: yes
  
  lines:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: lines-of-code.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_lines: yes

  habits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: classic
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
  
  achievements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
  
  contributions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: contributions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_notable: yes
          plugin_notable_from: all
